version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - 3304:3306
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: docker.io/bitnami/suitecrm:7
    ports:
      - '9017:8080'
      - '9018:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=${MARIADB_USER}
      - SUITECRM_DATABASE_NAME=${MARIADB_DATABASE}
      - SUITECRM_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - SUITECRM_USERNAME=${SUITECRM_USERNAME}
      - SUITECRM_PASSWORD=${SUITECRM_PASSWORD}
      - SUITECRM_EMAIL=djay@innotech.io
    volumes:
      - './suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb
#volumes:
#  mariadb_data:
#    driver: local
#  suitecrm_data:
#    driver: local